language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm run build
  - npm run deploy

env:
  global:
    - NODE_ENV=production
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
