dist: trusty
sudo: false

language: node_js
node_js:
  - 6
cache: yarn

addons:
  ssh_known_hosts: poker4.fun

before_script:
  - openssl aes-256-cbc -K $encrypted_edffe1b3d92e_key -iv $encrypted_edffe1b3d92e_iv
    -in deploy_key.enc -out ~/.ssh/deploy_key -d
  - chmod 600 ~/.ssh/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/deploy_key

script:
  - yarn test
  - yarn build

deploy:
  - provider: surge
    project: ./build/
    domain: ifs49f-poker.surge.sh
    skip_cleanup: true
  - provider: script
    script: rsync -r --delete-after --quiet ./build/. deploy@poker4.fun:/websites/poker
    skip_cleanup: true
    on:
      branch: new-server
