dist: trusty
sudo: false

language: node_js
node_js:
  - 6
cache: yarn

script:
  - yarn test
  - yarn build

# https://surge.sh/help/adding-a-200-page-for-client-side-routing
before_deploy:
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: ifs49f-poker.surge.sh
  skip_cleanup: true
  on: master
